blueprint:
  name: Presence-Based Automation
  description: >
    Schaltet basierend auf der Anwesenheit oder Abwesenheit einer Person Entitäten ein oder aus.
  domain: automation
  input:
    person_entity:
      name: Person Sensor
      description: Der Personen-Sensor, der überwacht werden soll.
      selector:
        entity:
          domain: person
    light_sensor:
      name: Licht Sensor
      description: Der Lichtsensor, der für die Helligkeitsüberprüfung verwendet wird (optional).
      selector:
        entity:
          domain: sensor
      default: ""
    brightness_threshold:
      name: Helligkeits-Schwellenwert
      description: Der Helligkeitswert, unter dem die Lichter eingeschaltet werden (optional).
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: "lx"
      default: 0
    binary_sensor:
      name: Binary Sensor
      description: Der Binary-Sensor, dessen Status überprüft werden soll (optional).
        OFF = ausschalten; ON = nichts unternehmen
      selector:
        entity:
          domain: binary_sensor
      default: ""
    entities_on_presence:
      name: Entitäten bei Anwesenheit einschalten
      description: Die Entitäten, die bei Anwesenheit eingeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
              - media_player
      default: {}
    special_entities_on_presence:
      name: Entitäten bei Anwesenheit nach Helligkeit einschalten
      description: Die Entitäten, die bei Anwesenheit unter berücksichtigung der Helligkeit eingeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
              - media_player
      default: {}
    entities_on_absence:
      name: Entitäten bei Abwesenheit ausschalten
      description: Die Entitäten, die bei Abwesenheit ausgeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
              - media_player
      default: {}
    special_entities_on_absence:
      name: Entitäten bei Abwesenheit gesteuert ausschalten
      description: Die Entitäten, die bei Abwesenheit unter berücksichtigung eines Binary-Sensors ausgeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
              - media_player
      default: {}

trigger:
  - platform: state
    entity_id: !input person_entity
    from: null
    to: null

variables:
  light_sensor: !input light_sensor
  brightness_threshold: !input brightness_threshold
  binary_sensor: !input binary_sensor
  entities_on_presence: !input entities_on_presence
  special_entities_on_presence: !input special_entities_on_presence
  entities_on_absence: !input entities_on_absence
  special_entities_on_absence: !input special_entities_on_absence

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state(trigger.to_state.state, 'home') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ entities_on_presence | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target: !input entities_on_presence
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ light_sensor and (states(light_sensor) | float < brightness_threshold) and special_entities_on_presence | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target: !input special_entities_on_presence
      - conditions:
          - condition: template
            value_template: "{{ is_state(trigger.to_state.state, 'not_home') }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ entities_on_absence | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_off
                    target: !input entities_on_absence
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ binary_sensor and is_state(binary_sensor, 'off') and special_entities_on_absence | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_off
                    target: !input special_entities_on_absence
mode: single
