blueprint:
  name: Presence-Based Automation
  description: >
    Schaltet basierend auf der Anwesenheit oder Abwesenheit einer Person in einer bestimmten Zone beliebig viele Switch- und Light-Entitäten ein oder aus.
  domain: automation
  input:
    person_entity:
      name: Person Sensor
      description: Der Personen-Sensor, der überwacht werden soll.
      selector:
        entity:
          domain: person
    zone_entity:
      name: Zone
      description: Die Zone, die überwacht werden soll.
      selector:
        entity:
          domain: zone
    entities_on_presence:
      name: Entitäten bei Anwesenheit
      description: Die Entitäten (Schalter und Lichter), die bei Anwesenheit eingeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
      default: []
    special_entities_on_presence:
      name: Besondere Entitäten bei Anwesenheit
      description: Die Entitäten, die bei Anwesenheit unter speziellen Bedingungen eingeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
      default: []
    entities_on_absence:
      name: Entitäten bei Abwesenheit
      description: Die Entitäten (Schalter und Lichter), die bei Abwesenheit ausgeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
      default: []
    special_entities_on_absence:
      name: Besondere Entitäten bei Abwesenheit
      description: Die Entitäten, die bei Abwesenheit unter speziellen Bedingungen ausgeschaltet werden sollen.
      selector:
        target:
          entity:
            domain:
              - switch
              - light
      default: []
    light_sensor:
      name: Licht Sensor
      description: Der Lichtsensor, der für die Helligkeitsüberprüfung verwendet wird (optional).
      selector:
        entity:
          domain: sensor
      default: ""
    brightness_threshold:
      name: Helligkeits-Schwellenwert
      description: Der Helligkeitswert, unter dem die Lichter eingeschaltet werden (optional).
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: "lx"
      default: 0
    binary_sensor:
      name: Binary Sensor
      description: Der Binary-Sensor, dessen Status überprüft werden soll (optional).
      selector:
        entity:
          domain: binary_sensor
      default: ""

trigger:
  - platform: state
    entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  light_sensor: !input light_sensor
  brightness_threshold: !input brightness_threshold
  entities_on_presence: !input entities_on_presence
  special_entities_on_presence: !input special_entities_on_presence
  entities_on_absence: !input entities_on_absence
  special_entities_on_absence: !input special_entities_on_absence
  binary_sensor: !input binary_sensor

condition: []

action:
  - delay: "00:00:10"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id in state_attr(zone_entity, 'persons') }}"
        sequence:
          - service: homeassistant.turn_on
            target: !input entities_on_presence
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ light_sensor and (states(light_sensor) | float < brightness_threshold) }}"
                sequence:
                  - service: homeassistant.turn_on
                    target: !input special_entities_on_presence
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id not in state_attr(zone_entity, 'persons') }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input entities_on_absence
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ binary_sensor and is_state(binary_sensor, 'off') }}"
                sequence:
                  - service: homeassistant.turn_off
                    target: !input special_entities_on_absence
mode: single
