blueprint:
  name: Select und Schalter Synchronisierung
  description: Synchronisiert einen input_select mit einem Schalter (switch). Wenn input_select auf Automatik steht, wird der Schalter abhängig vom Energieverbrauch geschaltet. Änderungen am Schalter beeinflussen den Select nur bei manueller Bedienung – ausgenommen definierte Benutzer.
  domain: automation
  input:
    select_entity:
      name: Select Helfer
      description: Wähle den input_select mit den Optionen Automatik, Ein, Aus
      selector:
        entity:
          domain: input_select
    switch_entity:
      name: Schalter
      description: Wähle den Schalter, der mit dem Select gekoppelt werden soll
      selector:
        entity:
          domain: switch
    ignored_users:
      name: Ignorierte Benutzer
      description: Eine Liste von Benutzer-IDs (eine pro Zeile)
      default: ""
      selector:
        text:
          multiline: true
    power_sensor:
      name: Energiesensor
      description: Sensor mit der aktuellen Leistung (negativ = Einspeisung, positiv = Bezug)
      selector:
        entity:
          domain: sensor
    einspeisungsschwelle:
      name: Schwellenwert Einspeisung
      description: Schwellwert in Watt, unter dem der Schalter bei Automatik eingeschaltet wird
      default: -100
      selector:
        number:
          min: -2000
          max: 1000
          unit_of_measurement: W
          mode: slider

mode: restart

variables:
  select_id: !input select_entity
  switch_id: !input switch_entity
  power_sensor: !input power_sensor
  einspeisungsschwelle: !input einspeisungsschwelle
  ignored_users_raw: !input ignored_users
  ignored_users: >-
    {{ ignored_users_raw.split('\n') | map('trim') | reject('equalto', '') | list }}

trigger:
  - platform: state
    entity_id: !input select_entity
  - platform: state
    entity_id: !input switch_entity
  - platform: state
    entity_id: !input power_sensor
    for:
      seconds: 15

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id == switch_id
                 and trigger.to_state.context.user_id is not none
                 and trigger.to_state.context.user_id not in ignored_users }}
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input select_entity
            data:
              option: >
                {{ "Ein" if trigger.to_state.state == "on" else "Aus" }}

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id == select_id }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.to_state.state == "Ein" }}
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input switch_entity
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.to_state.state == "Aus" }}
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input switch_entity
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.to_state.state == "Automatik" }}
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ states(power_sensor) | float(default=9999) < einspeisungsschwelle }}
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input switch_entity
                      - conditions:
                          - condition: template
                            value_template: >
                              {{ states(power_sensor) | float(default=0) >= einspeisungsschwelle }}
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input switch_entity
